"""
CAN IDs, pneumatic channels, and shared motor constants.

Drivetrain CAN IDs (swerve motors, encoders, Pigeon 2) are defined in
generated/tuner_constants.py — that file is auto-generated by CTRE Tuner X.
"""

# Motor feed-forward
NEO_FREE_SPEED_RPM = 5767  # NEO motor free speed for velocity FF calculation


class CANIds:
    # Shooter — two motors on shared flywheel shaft
    # LEFT
    SHOOTER_LEADER = 47  # VALIDATED
    # RIGHT
    SHOOTER_FOLLOWER = 43  # VALIDATED

    # Indexer — single brushed conveyor motor
    INDEXER = 42  # VALIDATED

    # Intake — arm (position) + roller (velocity)
    INTAKE_ROLLER = 44  # VALIDATED
    INTAKE_ARM = 46  # VALIDATED

    # Hood — adjustable shooter angle
    HOOD = 45  # VALIDATED

    # Kicker — two motors on shared shaft feeding into shooter
    # RIGHT
    KICKER_LEADER = 41  # VALIDATED
    # LEFT
    KICKER_FOLLOWER = 48  # VALIDATED


class PneumaticChannels:
    # Climber solenoid on CTRE PCM
    CLIMBER_SOLENOID = 2
